### ISSUE TITLE
Issue with terminado dependancy

### ISSUE THREAD

**Issue by ktechmidas** [AdaptiveScale/lxdui#205]
So I installed setuptools and am now running setup.py, however I'm running into an error that's stopping the install. Any ideas how I get it to skip the tests that aren't included anyway...?

**Searching for terminado
Reading https://pypi.python.org/simple/terminado/
Best match: terminado 0.8.1
Downloading https://files.pythonhosted.org/packages/67/84/ce0ebd0f60e1cbe040f8e065eef7063855d59d9cf5e6438b3f8439fc7e15/terminado-0.8.1.tar.gz#sha256=55abf9ade563b8f9be1f34e4233c7b7bde726059947a593322e8a553cc4c067a
Processing terminado-0.8.1.tar.gz
Writing /tmp/easy_install-kz_hozdu/terminado-0.8.1/setup.cfg
Running terminado-0.8.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-kz_hozdu/terminado-0.8.1/egg-dist-tmp-5xwou0_v
error: Setup script exited with error: can't copy 'terminado/tests': doesn't exist or not a regular file**

**Comment by ktechmidas** [comment]
I think it was in this commit:

https://github.com/AdaptiveScale/lxdui/commit/4ec1faffe21af1068df4c32c8b521baae291db54

**Comment by ktechmidas** [comment]
It appears to work just fine if I run "pip install ." from the directory, rather than "python3 setup.py install" https://github.com/AdaptiveScale/lxdui/wiki/Installing-LXDUI-2.0

They both do the same, but pip install . is much better as it uses pip rather than easy_install...

**Comment by vhajdari** [comment]
Hi @ktechmidas,  documentation always seems to lag behind a bit 😄.

Presently the focus has been on getting the support built in so that everything runs natively in a snap package in `strict` confinement mode.  This has proven to be a bit more challenging than expected, but good forward progress is being made.  After the next release you should see a `pip` package as well as a `snap` package which should make the install experience significantly better.
