### ISSUE TITLE
Model problem

### ISSUE THREAD

**Issue by condector** [AdaptiveScale/lxdui#221]
```
/usr/local/lib/python3.5/dist-packages/pylxd-2.2.7-py3.5.egg/pylxd/models/_model.py:116: UserWarning: Attempted to set unknown attribute "location" on instance of "Container"
  key, self.__class__.__name__
```

During execution, I received this error. The problem here occurs when I open the interface from one container and click or try to save a snapshot or access the file browser.

**Comment by vhajdari** [comment]
Hi @condector,

When do you encounter this error, when you first start LXDUI or while performing some operation?  Does it actually cause a failure of some kind?

**Comment by condector** [comment]
Hi @vhajdari,

   When clicking on a container and experiment the file browser interface that shows the filesystem. The LXDUI show this error and stop to work. Appears to be processing something and nothing work until I kill LXDUI and start it again.

Could I provide some information about LXDUI or Python that helps?

**Comment by condector** [comment]
Using the File Manager interface or trying to do a snapshot. The web interface shows this error and stops to work correctly.

**Comment by Anachron** [comment]
I'm getting the same error when trying to open a terminal of a running (or not-running) container.

**Comment by vhajdari** [comment]
Check out the solution described in this issue [https://github.com/AdaptiveScale/lxdui/issues/275](https://github.com/AdaptiveScale/lxdui/issues/275) to see it that might provide some clues on what to troubleshoot.

**Comment by Anachron** [comment]
Sorry but I don‘t get how that is supposed to help? I‘m running it in the foreground, the $PATH is already correct.

**Comment by vhajdari** [comment]
@Anachron, its not clear from your problem statement if you are running LXD as an APT packaged install or as a Snap.  Snaps make it convenient to run LXD easily without having to deal with other dependencies, but they also limit what you can do with within the protected app container.  [Terminado](https://github.com/jupyter/terminado), the web terminal lib used by LXDUI, needs access to some of the underlying resources exposed in the LXD snap.  

Sometimes it's a matter of permissions, how you installed everything and under what user account, and how you stared the services. Other times it's a matter of having your environment configured properly for the session so that the executables have access to the requisite paths.

Without an intrinsic understanding of exactly how you have set up your environment, my recommendation is to contact the [Terminado](https://github.com/jupyter/terminado) maintainers and see if perhaps they might be able to provide any pointers. 

Alternatively, if your containers are on a flat network (the same network for the containers as well as the LXD host) then you should be able to just use your standard Linux Bash shell to access the containers.

Hope this helps somewhat.

**Comment by Anachron** [comment]
I've installed `LXC` and `LXD` as package in my distribution. No snap or alike. 

There are no problems accessing my containers using pure `lxc` commands from the console. Everything is fine when using `lxc`.

**Comment by joekrom** [comment]
@vhajdari  
Hi i am not able to access terminal container when  running lxdui under systemd 
my home user can get access to lxc and lxd without any problem, but i am running through this permission issues one way or another

**Comment by vhajdari** [comment]
By terminal you mean within the browser, correct? Are you running lxdui as
a snap installation or standard pip install?  Can you list out the steps of
what you've done so that we can assist you?

**Comment by joekrom** [comment]
Yes i mean i cant open the terminal of a container trough the browser 
Installation procedure  unsing ansible playbook 

1 - update apt repository and install required package for installing git 
2 - clone lxdui from the repo 
3 - install upgrade pip , open the cd lxdui and install the required package 
4 - copy the lxdui.service file config on the /etc/systemd/system/ directory 
5 - enable  and start lxdui service  

![lxdui_terminal_issues](https://user-images.githubusercontent.com/37833979/131703506-bc73c1f8-0087-484e-bdfa-3ad098165618.PNG)

**Comment by vhajdari** [comment]
I think it may be a permission issue with LXD running in snap.  Try
deploying LDX snap with --classic to see if that makes a difference.
Compare your Ansible playbook with this install script
<https://gist.github.com/vhajdari/f1a4bbfc30e1096ed285ffb2772f8f2f> that I
created a while back--look at line 99
<https://gist.github.com/vhajdari/f1a4bbfc30e1096ed285ffb2772f8f2f#file-lxdui-install-sh-L99>
.

**Comment by joekrom** [comment]
thx i will try that on my local server, many containers are already in production on the principal server 
I think the problem is that snap can't access the system because default mode is strict.  May be the classic will give me a better 
result. 
Another point is that when installing the packages using pip install --user , there are isolating on a specific user , and the  app running through systemd is trying to access the packages located on the root which are not of course installed
