### ISSUE TITLE
Issue with User Accounts when running as a .service

### ISSUE THREAD

**Issue by Snowheart119** [AdaptiveScale/lxdui#241]
Hi

I'm a little new to this so apologies if I'm going about this the wrong way. I am having an issue where if I start lxdui using lxdui start or the run.py script and make changes to add/change the admin account password then these work fine BUT what I want to do is have lxdui run at startup when my container host starts. 

So I added it as a service by creating the following file in /lib/systemd/system called lxdui.service

[Unit]
Description=LXDUI Service
After=multi-user.target
Conflicts=getty@tty1.service

[Service]
Type=simple
ExecStart=/usr/bin/python3 /bin/lxdui/run.py start
StandardInput=tty-force

[Install]
WantedBy=multi-user.target

Then running the following to reload systemd:
sudo systemctl daemon-reload
sudo systemctl enable lxdui.service
sudo systemctl start lxdui.service

This works in that lxdui runs at startup of the host and doesn't require me to open an SSH or console session to the host to keep it running BUT if I make a change to admin password or add another user the Web UI doesn't seem to respect this. It just keeps going back to admin/admin and the new accounts don't work at all. 

If I start lxdui using lxdui start though it works fine. 

As such I'm sure I'm doing something stupid but I have no idea what...

Any insight would be much appreciated!

Thanks

I'm running this on Ubuntu 18.04.1 LTS

**Comment by vhajdari** [comment]
Hi @Snowheart119,

Do you see the users being added to the auth.conf file when you are running it as a service?  You should check what user the service is being run as, as it may be a permission issue.

**Comment by Snowheart119** [comment]
Hi @vhajdari 

Just checked. So when running as a service no they are not added and no changes seemed to save back to auth.conf after running the command to change the password or add a user. 

Root is the owner of the lxdui top level folder where everything lives and I thought systemd ran as root and therefore would run the service as root so I'm a little puzzled to be honest.

**Comment by ivo1981** [comment]
l had the same problem yesterday figured I'd wait a day to see if a fix would be posted...
since I really hate it when github issues are not addressed I figured i'd post a fix.
I haven't tested it extensively, but so far it seems to work...
you say you're new to this so i'll break it down
I'm on ubuntu server 16.04, so if you are not your milage may vary ;)

check the group that owns python:
ls -l /usr/local/lib/python3.5/dist-packages/
in my case it was "staff"

add your user to the group:
sudo usermod -a -G staff <my user>

set ownership of the egg to my user:
sudo chown -R $USER /usr/local/lib/python3.5/dist-packages/LXDUI-2.1.2-py3.5.egg

set ownership of logging to my user:
sudo chown -R $USER /usr/lib/python3.5/logging

create a service that is run as user; there's a few differences with your script as i use the native "lxdui" command instead of the run.py:

sudo nano /lib/systemd/system/lxduistart.service
put this inside and swap <my user> for your user:

[Unit]
Description=Web UI for the native Linux container technology LXD/LXC
After=network.target lxd.service
Requires=lxd.service

[Service]
Type=simple
User=<my user>
PIDFile=/run/lxdui/lxdui.pid
ExecStart=/usr/local/bin/lxdui start
ExecStop=/usr/local/bin/lxdui stop

[Install]
WantedBy=multi-user.target



save the file (ctrl+x with nano)

use "sudo sytemctl enable lxduistart.service" to enable the service on boot
use "sudo sytemctl status lxduistart.service" to check if it's running
use "sudo sytemctl start lxduistart.service" to start the service manually
use "sudo sytemctl enable lxduistart.service" to stop the service

Hope that helps

**Comment by Snowheart119** [comment]
@ivo1981

Thanks. That makes sense. I will give this a try when I get home this evening.

**Comment by Snowheart119** [comment]
@ivo1981 
That sorted it! I did have an issue where I could the service to run as root but not start as my user initially but I fixed this by changing the owner to the lxdui folder to my user (previously it had been root). 

I can now change user passwords and add users without issue. 

Thank you very much for your help!

**Comment by ivo1981** [comment]
you're welcome!
as a general rule; only use root when you have no other choice!
doing stuff with the root user not only creates lots of problems, it also creates lots of security risks that are unnecessary and linux security is a very tough subject. so ty to avoid root as much as possible especially on production systems ;)

**Comment by vhajdari** [comment]
thanks for pitching in @ivo1981

**Comment by chrispe-lab** [comment]
For anyone else struggling with this issue of having the GUI run as a service on boot I'm using this config and now it works flawlessly:

[Unit]
Description=Web UI for the native Linux container technology LXD/LXC
After=network.target snapd.service
Requires=snapd.service

[Service]
Type=simple
User=USERNAME
PIDFile=/run/lxdui/lxdui.pid
ExecStart=/usr/bin/python3 /home/USERNAME/lxdui/run.py start
ExecStop=/usr/bin/python3 /home/USERNAME/lxdui/run.py stop

[Install]
WantedBy=multi-user.target

I've most probably also changed the ownership of the folders when trying to problem solve this.
