### ISSUE TITLE
Get Session Username

### ISSUE THREAD

**Issue by otaviomarco** [AdaptiveScale/lxdui#244]
Hello. I want to insert on container schema the username who created it. How i can get the session username at this point?

**Comment by vhajdari** [comment]
Hi @otaviomarco,

I'm not sure what you mean by schema.  Are you referring to the YAML representation that LXD creates for a container so that you can update the container metadata -- e.g. `lxc config metadata edit <container_name>`?  

If you need to grab the authenticated user in the browser you can use the JavaScript function: `sessionStorage.getItem("user")`

**Comment by otaviomarco** [comment]
Hi @vhajdari. Thanks for reply.

I actually need, when creating a container, to write the user who created it. With this i can restrict user access.

**Comment by vhajdari** [comment]
@otaviomarco,

What's not clear is, write username to where?  How would you do this if you were to create a container, say with `lxc launch ubuntu:16.04 myContainer`?

**Comment by vhajdari** [comment]
OK I see.  You are asking about role based access controls (RBAC).  So, the simple answer is you can't do it today, but we plan on introducing RBAC in the 2.4 or 2.5 timeframe.  

We tried to make LXDUI as simple as possible, an extension of LXD, by providing a visual interface on top of LXD using LXD's API.  Since LXD does not provide an API for RBAC we have no way of exposing that in LXDUI.  In the future we'll expand on the platform to include state persistence (a.k.a database) so that authentication and authorization can be applied to entities within the application.  If LXD exposes such an API we'd most likely use that instead. 

With that said, I'd recommend dropping a line to the fine folks at [https://discuss.linuxcontainers.org/](https://discuss.linuxcontainers.org/) to see if they may have an alternative for you.

Hope that helps!

**Comment by otaviomarco** [comment]
No problem. Thanks for your time. ;)
